from PIL import Image
import os
import shutil

class Photo:
    def __init__(self, name, path):
        self.id_ = name[:-4]
        self.name = name
        self.path = path
        self.real_dir = os.path.join(path,name)
    def __repr__(self):
        return self.name
    def move(self, new_real_dir):
        shutil.move(self.real_dir,new_real_dir)
        self.real_dir = new_real_dir
        
class Folder:
    def __init__(self, path):
        self.path = path
        self.name = os.path.basename(path)
        self.file = []
        for file in os.listdir(path):
            if file[-3:] == 'png':
                self.file.append(Photo(file,path))
        
    def __repr__(self):
        return self.name
    
    def creat_config(self):
        c = os.path.join(self.path, 'config.xml')
        config = open(c,'w')
        for i in ['<record>\n', '\t<!-- resource manager options -->\n', '\n', '\t<!-- dont preload anything in this folder -->\n', '\t<boolean id="preload" value="false"/>\n', '\n', '\t<!-- turn off auto mapping -->\n', '\t<boolean id="amap" value="false"/>\n', '\n', '\t<!-- logo mappings -->\n', '\t<!-- the following XML maps pictures inside this folder into other positions\n', '\t\t\t in the resource system, which allows this folder to be dropped into any\n', '\t\t\t place in the graphics folder and still have the game pick up the graphics\n', '\t\t\t files from the correct places\n', '\t-->\n', '\n', '\t<list id="maps">\n', '\t\t<!-- Auto generated by Mingren Chen -->\n']:
            config.writelines(i)
        for photo in self.file:
            write_stuff = '\t\t<record from="0" to="graphics/pictures/person/0/portrait"/>\n'
            write_list = write_stuff.split("/")
            write_list[-3] = photo.id_
            config.writelines('/'.join(write_list))
        config.writelines('/'.join(['\t</list>\n', '</record>']))
        config.close()
    


if __name__ == "__main__":
    fm_filepath = r"C:\Users\Harru\Documents\Sports Interactive\Football Manager 2017\graphics\players"
    folder_list = os.listdir(fm_filepath)
    photo_list = []
    for folder in folder_list:
        face_filepath = os.path.join(fm_filepath, folder)
        if os.path.isdir(face_filepath):
            for photo in os.listdir(face_filepath):
                if photo[-3:] == 'png':
                    photo_list.append(Photo(photo,face_filepath))
    new_folder_name = []
    for j in range(50):
        current_folder_name = 'face'+str(j)
        current_folder_dir = os.path.join(fm_filepath,current_folder_name)
        new_folder_name.append(current_folder_dir)
        if not os.path.exists(current_folder_dir):
            os.mkdir(current_folder_dir)
        for i in range(20000):
            photo_list[0].move(os.path.join(current_folder_dir,photo_list[0].name))
            photo_list.pop(0)
            
            

# with Image.open(fm_filepath) as img:
#     width, height = img.size
